"""empty message

Revision ID: 6b3c69cb53d1
Revises: c000bbd3d36c
Create Date: 2018-08-14 16:26:47.564699

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b3c69cb53d1'
down_revision = 'c000bbd3d36c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'hunters', ['position'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'hunters', type_='unique')
    # ### end Alembic commands ###
