"""empty message

Revision ID: c000bbd3d36c
Revises: bd5e75901a40
Create Date: 2018-08-14 15:47:34.958026

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c000bbd3d36c'
down_revision = 'bd5e75901a40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hunters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=True),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('lastPosition', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hunters')
    # ### end Alembic commands ###
