"""empty message

Revision ID: fcc0b59b1647
Revises: af0565d5a5d9
Create Date: 2018-08-06 10:37:42.048346

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fcc0b59b1647'
down_revision = 'af0565d5a5d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('departments', sa.Column('imageUrl', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('departments', 'imageUrl')
    # ### end Alembic commands ###
